default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: recipe_app_dev
  username: postgres
  password: NQ1234ta
  host: localhost

test:
  <<: *default
  database: recipe_app_test
  username: postgres
  password: NQ1234ta
  host: localhost

production:
  <<: *default
  database: recipe_app_prod
  username: sagie
  password: password
  host: localhost




